name: Hello Github actions

on: 
  push:
    - main
  pull_request:
    - main
  workflow_dispatch:

jobs:
  Hello-job:
    runs-on: ubuntu-latest

  steps:
    - name: checkout Codigo
      uses: actions/checkout@v4
    
    - name: Executar Hello World
      run: echo " Hello Github Actions "
    
    - name: Mostrar informações de sistema
      run: |
        echo " Sistema Operacional: ${{ runner.os}} "
        echo " Diretorio Atual: ${pwd} "
        echo " Data atual: $(date) "
        echo " Usuario: $ (whoami) "
    
    - name: Lista arquivos do repositorio
      run: ls -la

    - name: Comandos multiplos
      run: |
        echo "Este é o lab 01 do curso de github actions"
        echo "Workflow executado com sucesso"
        echo "Pronto para os proximos desafio"
           