on:
  schedule:
    - cron: '55 21 * * *' #Executa as 21:51 horario Brasilia (utc)
  workflow_dispatch:

jobs:
  secheduled-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Informações do schedule
        run: |
          echo "Worflow disparado por schedule"
          echo "Data atual: $(date)"
          echo "Horario UTC: $(date-u)"
          echo "Timezone: $(date+%z)"
        
      - name: Relatorio diario automatizado
        run: |
          echo "Relatorio diario automatizado"
          echo "============================="
          echo "Total de commits: $(git rev-lis --all --count)"
          echo "Contribuidores únicos: $(git shortlog -sn | wc -l)"
          echo "Último commit: $(git log -l --pretty=format: '%h - %s (%an, %ar)')"